### ISSUE TITLE
Absolute paths in "--dir" are concatenated wrong

### ISSUE THREAD

**Issue by BigETI** [Southclaws/sampctl#17]
Specifying an absolute path in "--dir" doesn't work.

```
panic: GetFileAttributesEx X:\cs\SAMPLauncherNET\SAMPLauncherNET\bin\Debug\X:\cs\SAMPLauncherNET\SAMPLauncherNET\bin\Debug\development\samp-npc.exe: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch.

goroutine 1 [running]:
main.exists(0x115acf80, 0x78, 0x2)
        C:/Users/south/go/src/github.com/Southclaws/sampctl/download.go:211 +0x74
main.ValidateServerDir(0x114f1500, 0x6b, 0x7670d6, 0x5, 0x30, 0x31, 0xffffffe1)
        C:/Users/south/go/src/github.com/Southclaws/sampctl/download.go:184 +0xa4
main.Run(0x76ea79, 0x16, 0x7670d6, 0x5, 0x114f1500, 0x6b, 0xdb4730, 0x0)
        C:/Users/south/go/src/github.com/Southclaws/sampctl/run.go:15 +0x53
main.main.func2(0x111aa420, 0x0, 0x111aa420)
        C:/Users/south/go/src/github.com/Southclaws/sampctl/main.go:84 +0x173
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x700a40, 0x114446b0, 0x111aa420, 0x112b6600, 0x0)
        C:/Users/south/go/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xa2
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x766b8c, 0x3, 0x0, 0x0, 0x114446c0, 0x1, 0x1, 0x779ee2, 0x34, 0x0, ...)
        C:/Users/south/go/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0x999
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0x114c8460, 0x11179aa0, 0x4, 0x4, 0x0, 0x0)
        C:/Users/south/go/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x606
main.main()
        C:/Users/south/go/src/github.com/Southclaws/sampctl/main.go:116 +0x892
```

Relative paths work fine, though.

**Comment by Southclaws** [comment]
I thought there wasn't an Abs function in Go so I tried to write my own but [there is](https://golang.org/pkg/path/filepath/#Abs) so I'll just use that!

**Comment by Southclaws** [comment]
1.2.2 should resolve this.
