### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AGraber** [Southclaws/sampctl#218]
One of my private Travis CI builds that use sampctl crashed on `sampctl package build`:

```
$ sampctl package build
Failed to find configuration /home/travis/.samp/config.toml
Failed to find configuration /home/travis/.samp/config.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x98561c]
goroutine 1 [running]:
main.packageBuild(0xc4200d8840, 0x0, 0xc4200d8840)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/package_build.go:63 +0x10bc
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xa18c20, 0xb50788, 0xc4200d8840, 0xc420075400, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xc8
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xb2285d, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb39cfb, 0x22, 0x0, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0xa36
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0xc4200aab60, 0xc4200d8160, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:379 +0xa10
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.startApp(0xb24e32, 0x7, 0x0, 0x0, 0xc4206b62a0, 0x1, 0x1, 0xb34c52, 0x1c, 0x0, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:298 +0x8d9
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xb24e32, 0x7, 0x0, 0x0, 0xc4206b62a0, 0x1, 0x1, 0xb34c52, 0x1c, 0x0, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:98 +0x1246
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200aa820, 0xc420086060, 0x3, 0x3, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6a0
main.main()
	/home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:297 +0x197f
The command "sampctl package build" exited with 2.
```

Also tried to build with one build option from `samp.json` (`sampctl package build live`) but the crash was identical to this one.

It seems that I can't reproduce this anywhere else, so here is some more info about the Travis CI thing:
```
Build language: cpp
Build group: stable
Build dist: trusty
Build id: 79716507
Job id: 135846670
Runtime kernel version: 4.4.0-101-generic
travis-build version: 5aef38fe4
Build image provisioning date and time
Tue Dec  5 19:58:13 UTC 2017
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Cookbooks Version
7c2c6a6 https://github.com/travis-ci/travis-cookbooks/tree/7c2c6a6
git version
git version 2.15.1
bash version
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)
gcc version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:38 2017
 OS/Arch:      linux/amd64
```

**Comment by AGraber** [comment]
I've confirmed this doesn't happen in 1.8.19

**Comment by Southclaws** [comment]
should be resolved in next release, thanks for reporting!
