### ISSUE TITLE
Panic! at the disco

### ISSUE THREAD

**Issue by Cezear** [Southclaws/sampctl#220]
Error given on build:
```
panic: The filename, directory name, or volume label syntax is incorrect.
```

Other error info generated by sampctl
```
goroutine 1 [running]:
github.com/Southclaws/sampctl/util.FullPath(0x0, 0x0, 0x45, 0xc042054780)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/util/util.go:73 +0x7d
github.com/Southclaws/sampctl/rook.(*PackageContext).buildPrepare(0xc0420ab080, 0xbd2460, 0xc0420200d0, 0x0, 0x0, 0xb30100, 0xc04259a1a0, 0xa2d060, 0xbc8cd0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/rook/build.go:245 +0xb9
github.com/Southclaws/sampctl/rook.(*PackageContext).Build(0xc0420ab080, 0xbd2460, 0xc0420200d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0421aafa0, 0x14, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/rook/build.go:39 +0xaa
main.packageBuild(0xc0420a6840, 0x0, 0xc0420a6840)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/package_build.go:91 +0x4f3
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0xa3f5e0, 0xb7b068, 0xc0420a6840, 0xc04245d800, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xcf
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xb4bcc1, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb643cb, 0x22, 0x0, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0xa3d
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0xc04208c820, 0xc0420a6160, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:379 +0xa17
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.startApp(0xb4e22f, 0x7, 0x0, 0x0, 0xc0426ce360, 0x1, 0x1, 0xb5f292, 0x1c, 0x0, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:298 +0x8e0
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0xb4e22f, 0x7, 0x0, 0x0, 0xc0426ce360, 0x1, 0x1, 0xb5f292, 0x1c, 0x0, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:98 +0x124d
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc04208c1a0, 0xc0420500c0, 0x3, 0x4, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6a7
main.main()
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:301 +0x1986
```

**Comment by Cezear** [comment]
Suppose adding what I did before this error threw would help:
All I did was edit pawn.json, added the MySQL plugin, ran the ensure command and you have it.

**Comment by Southclaws** [comment]
Can you post your `pawn.json` contents?

**Comment by Cezear** [comment]
```json
{
	"user": "Cezear",
	"repo": "dealership-system",
	"input": "filterscripts/convert.pwn",
	"output": "filterscripts/convert.amx",
	"dependencies": [
		"sampctl/samp-stdlib",
		"Southclaws/samp-ini:1.1.0",
		"Southclaws/zcmd",
		"maddinat0r/sscanf:v2.8.2",
		"Open-GTO/sa-mp-fixes",
		"Southclaws/pawn-fsutil:1.0.4",
		"pBlueG/SA-MP-MySQL:R41-4"
	],
	"local": true,
	"runtime": {
		"version": "0.3.DL",
		"mode": "server",
		"rcon_password": "password",
		"port": 7777,
		"maxplayers": 35,
		"language": "English",
		"gamemode": "grandlarc"
	}
}
```

I'll also note that making a new directory, copying everything over (all .pwn files, same .json, etc) worked with now issues.

**Comment by Southclaws** [comment]
That's strange, I'm not sure where the invalid syntax issue would come from. Since you said creating a new folder fixed it I can only assume it was a misconfiguration or bug in how Windows was treating that particular directory.
