### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by AGraber** [Southclaws/sampctl#225]
```
samp@oz:~# sampctl
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/Southclaws/sampctl/types.LoadOrCreateConfig(0xc420668f90, 0xb, 0x0, 0xc4204a3800, 0xc42053f8a0, 0x8dfe96)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/types/config.go:63 +0x6ac
main.main.func2(0xc4200c4160, 0xb50668, 0xc420098340)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:242 +0xe2
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc420098340, 0xc42001c1b0, 0x1, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:241 +0x6f0
main.main()
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:301 +0x197f
```

This also happened, before the another one. I think it didn't happen again because it already had "checked" for updates (although horribly failing), and maybe a config value was updated and it didn't check for updates anymore:

```
panic: runtime error: slice bounds out of range
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0x983d86]

goroutine 1 [running]:
main.CheckForUpdates(0xb9be60, 0x6)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:324 +0x96
main.main.func3(0xc4200c4160, 0xc420cd9580, 0x4013d1)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:296 +0x139
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run.func1(0xc4200984e0, 0xc4200c4160, 0xc420cd9bc0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:230 +0x3b
panic(0xa44be0, 0xf786f0)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505 +0x229
github.com/Southclaws/sampctl/types.LoadOrCreateConfig(0xc420358fc0, 0xb, 0x0, 0xc4206e2e00, 0xc420cd98a0, 0x8dfe96)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/types/config.go:63 +0x6ac
main.main.func2(0xc4200c4160, 0xb50668, 0xc4200984e0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:242 +0xe2
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200984e0, 0xc42001c1b0, 0x1, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:241 +0x6f0
main.main()
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:301 +0x197f
```

Slightly different variation of the previous one:
```
samp@oz:/home/OmegaZone# sampctl
panic: runtime error: slice bounds out of range
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x108 pc=0x983d86]

goroutine 1 [running]:
main.CheckForUpdates(0xb9be60, 0x6)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:324 +0x96
main.main.func3(0xc4200c4160, 0xc42064d580, 0x4013d1)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:296 +0x139
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run.func1(0                                                                                                                               xc4200984e0, 0xc4200c4160, 0xc42064dbc0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/ur                                                                                                                               fave/cli.v1/app.go:230 +0x3b
panic(0xa44be0, 0xf786f0)
        /home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:505                                                                                                                                +0x229
github.com/Southclaws/sampctl/types.LoadOrCreateConfig(0xc420678f90, 0xb, 0x0, 0                                                                                                                               xc420122600, 0xc42064d8a0, 0x8dfe96)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/types/config.go:63                                                                                                                                +0x6ac
main.main.func2(0xc4200c4160, 0xb50668, 0xc4200984e0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:242 +0xe2
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc4200                                                                                                                               984e0, 0xc42001c1b0, 0x1, 0x1, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/ur                                                                                                                               fave/cli.v1/app.go:241 +0x6f0
main.main()
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:301 +0x197
```
`sampctl -V` didn't stop working, so at least I could confirm this was happening in latest version:
```
samp@oz:~# sampctl -V
sampctl version 1.8.23
```

Some info about environment (Debian 9.5):
```
         _,met$$$$$gg.           root@oz
      ,g$$$$$$$$$$$$$$$P.        OS: Debian
    ,g$$P""       """Y$$.".      Kernel: x86_64 Linux 4.9.0-7-amd64
   ,$$P'              `$$$.      Uptime: 9h 31m
  ',$$P       ,ggs.     `$$b:    Packages: 378
  `d$$'     ,$P"'   .    $$$     Shell: bash 4.4.12
   $$P      d$'     ,    $$P     CPU: Common KVM @ 3.991GHz
   $$:      $$.   -    ,d$$'     RAM: 332MiB / 3954MiB
   $$\;      Y$b._   _,d$P'
   Y$$.    `.`"Y$$$$P"'
   `$$b      "-.__
    `Y$$
     `Y$$.
       `$$b.
         `Y$$b.
            `"Y$b._
                `""""
```

**Comment by Southclaws** [comment]
Looks like this code: https://github.com/Southclaws/sampctl/blob/master/main.go#L244 exited resulting in `gh` (GitHub client) to be nil.

**Comment by AGraber** [comment]
Seems that 0613377 fixes it

**Comment by Southclaws** [comment]
The `        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:324 +0x96` crash is unrelated to 0613377c0e4e51e77a818d23b88bfa5ee357937e so I'm reopening.
