### ISSUE TITLE
sampctl 1.8.30 panic

### ISSUE THREAD

**Issue by ADRFranklin** [Southclaws/sampctl#242]
Tried to run sampctl on my CI/CD build and this is what it outputted.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x848b70d]

goroutine 1 [running]:
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*PublicKeysCallback).ClientConfig(0x0, 0xf770b000, 0x0, 0x8056c4f)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/auth_method.go:232 +0x1d
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).connect(0x34ee43c0, 0xf75b0520, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:111 +0x42
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*runner).Command(0x19f0d8d0, 0x86fb3c4, 0xf, 0x34ee4390, 0xf75b0520, 0x0, 0x34ee4390, 0x19f62cf0, 0x86a63e0, 0x34ee4390)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:50 +0x82
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).newSession(0x19f0d8d8, 0x86fb3c4, 0xf, 0x34ee4390, 0xf75b0520, 0x0, 0x0, 0x0, 0x34ee4390)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go:112 +0x52
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).NewUploadPackSession(0x19f0d8d8, 0x34ee4390, 0xf75b0520, 0x0, 0x34ee4390, 0x0, 0x0, 0x1a6bda40)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go:89 +0x4b
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git%2ev4.newUploadPackSession(0x20825fc0, 0x3d, 0xf75b0520, 0x0, 0x1a7f0cb0, 0x0, 0x1, 0x805726c)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/remote.go:321 +0x7d
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git%2ev4.(*Remote).fetch(0x1a7f0d20, 0x87871a0, 0x19f1e0d8, 0x1aa8af4c, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/remote.go:259 +0xe9
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git%2ev4.(*Repository).fetchAndUpdateReferences(0x1c280d00, 0x87871a0, 0x19f1e0d8, 0x1aa8af4c, 0x86f2885, 0x4, 0x878a4a0, 0x1a7f0a50, 0x878a4a0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/repository.go:650 +0x8a
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git%2ev4.(*Repository).clone(0x1c280d00, 0x87871a0, 0x19f1e0d8, 0x1a006540, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/repository.go:521 +0x1ed
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git%2ev4.PlainCloneContext(0x87871a0, 0x19f1e0d8, 0x20825d40, 0x3e, 0x0, 0x1a006540, 0x86c1801, 0x1a6bda08, 0x1a006540)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/repository.go:353 +0x7e
github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git%2ev4.PlainClone(0x20825d40, 0x3e, 0x0, 0x1a006540, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/src-d/go-git.v4/repository.go:337 +0x4e
github.com/Southclaws/sampctl/rook.PackageContext.ensureRepoExists(0x1, 0x1a343640, 0x1d, 0x1a2ceea0, 0x2a, 0x1a2ce203, 0x4, 0x0, 0x0, 0x1a3357e8, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/rook/cache.go:223 +0x306
github.com/Southclaws/sampctl/rook.PackageContext.EnsureDependencyCached(0x1, 0x1a343640, 0x1d, 0x1a2ceea0, 0x2a, 0x1a2ce203, 0x4, 0x0, 0x0, 0x1a3357e8, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/rook/cache.go:184 +0xfc
github.com/Southclaws/sampctl/rook.(*PackageContext).EnsureDependenciesCached.func1(0x1a2cb784, 0x17, 0x1a2cb79c, 0xf, 0x1a2cb7ac, 0x11, 0x1a2cb79c, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/rook/cache.go:67 +0x10d6
github.com/Southclaws/sampctl/rook.(*PackageContext).EnsureDependenciesCached.func1(0x0, 0x0, 0x1a3357e8, 0x4, 0x1a3357ec, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/rook/cache.go:143 +0xd69
github.com/Southclaws/sampctl/rook.(*PackageContext).EnsureDependenciesCached(0x19fdc580, 0x2, 0x2)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/rook/cache.go:150 +0x1a2
github.com/Southclaws/sampctl/rook.NewPackageContext(0x19fd04d0, 0xf75b0520, 0x0, 0x1, 0x1a343640, 0x1d, 0x86f3723, 0x5, 0x1a3355c0, 0xb, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/rook/load.go:106 +0x400
main.packageEnsure(0x19fd06e0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/package_ensure.go:55 +0x1ce
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x86129c0, 0x87234a8, 0x19fd06e0, 0x1a33d300, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xa2
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x86f4402, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x87014da, 0x16, 0x0, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0x8e1
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0x19f64460, 0x19fd02c0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:379 +0x842
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.startApp(0x86f5ad2, 0x7, 0x0, 0x0, 0x1a3897e0, 0x1, 0x1, 0x8706be1, 0x1c, 0x0, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:298 +0x73d
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x86f5ad2, 0x7, 0x0, 0x0, 0x1a3897e0, 0x1, 0x1, 0x8706be1, 0x1c, 0x0, ...)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/command.go:98 +0xfda
github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0x19f642a0, 0x19f14080, 0x3, 0x4, 0x0, 0x0)
	/home/travis/gopath/src/github.com/Southclaws/sampctl/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x58b
main.main()
	/home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:307 +0x1529
ERROR: Job failed: exit code 1
```

**Comment by Southclaws** [comment]
src-d/go-git updated with breaking changes for some unknown reason. Might have to await a fix upstream or figure out a working version.

**Comment by Southclaws** [comment]
Can't seem to reproduce this with basic auth, it seems SSH is what has broken.

**Comment by Southclaws** [comment]
Potentially fixed this in dev

**Comment by Southclaws** [comment]
1.8.31 rolls back the version of src-d/go-git to 4.0.0-rc15, the latest is 4.6.0 so at some point I should look into upgrading with more unit tests to cover cases of potential crashes like this one.
