### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by Zorono** [Southclaws/sampctl#318]
```
D:\>D:\Testk\sampctl.exe p init
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x8efb99]

goroutine 1 [running]:
github.com/Southclaws/sampctl/rook.Init.func1(0x1273e180, 0x3c, 0x0, 0x0, 0xb04c
70, 0x12047c00, 0x0, 0x0)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/rook/initialise.go
:66 +0x39
path/filepath.walk(0x12731f40, 0x33, 0xb09860, 0x12733800, 0x121e0e20, 0x0, 0x0)

        /home/travis/.gimme/versions/go1.11.linux.amd64/src/path/filepath/path.g
o:378 +0x174
path/filepath.walk(0x12297f50, 0x29, 0xb09860, 0x12733740, 0x121e0e20, 0x0, 0x0)

        /home/travis/.gimme/versions/go1.11.linux.amd64/src/path/filepath/path.g
o:382 +0x1f1
path/filepath.walk(0x12297e30, 0x22, 0xb09860, 0x12733560, 0x121e0e20, 0x0, 0x0)

        /home/travis/.gimme/versions/go1.11.linux.amd64/src/path/filepath/path.g
o:382 +0x1f1
path/filepath.walk(0x1247f200, 0x1b, 0xb09860, 0x123abce0, 0x121e0e20, 0x0, 0x0)

        /home/travis/.gimme/versions/go1.11.linux.amd64/src/path/filepath/path.g
o:382 +0x1f1
path/filepath.walk(0x1247f100, 0x15, 0xb09860, 0x123ab9e0, 0x121e0e20, 0x0, 0x0)

        /home/travis/.gimme/versions/go1.11.linux.amd64/src/path/filepath/path.g
o:382 +0x1f1
path/filepath.walk(0x120e90d0, 0xd, 0xb09860, 0x12224420, 0x121e0e20, 0x0, 0x20)

        /home/travis/.gimme/versions/go1.11.linux.amd64/src/path/filepath/path.g
o:382 +0x1f1
path/filepath.Walk(0x120e90d0, 0xd, 0x121e0e20, 0x4, 0x1)
        /home/travis/.gimme/versions/go1.11.linux.amd64/src/path/filepath/path.g
o:404 +0xdf
github.com/Southclaws/sampctl/rook.Init(0xb07f80, 0x1204e07c, 0x120504d0, 0x120e
90d0, 0xd, 0x126e4a80, 0x0, 0x0, 0xa475b9, 0x7, ...)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/rook/initialise.go
:65 +0x125
main.packageInit(0x12050630, 0x0, 0x12050630)
        /home/travis/gopath/src/github.com/Southclaws/sampctl/package_init.go:50
 +0x1d5
gopkg.in/urfave/cli%2ev1.HandleAction(0x9769a0, 0xa73528, 0x12050630, 0x1220fe00
, 0x0)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0
xa2
gopkg.in/urfave/cli%2ev1.Command.Run(0xa462c2, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa
4f4ca, 0x14, 0x0, ...)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:21
0 +0x8d8
gopkg.in/urfave/cli%2ev1.(*App).RunAsSubcommand(0x12434380, 0x12050370, 0x0, 0x0
)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:379 +0
x6a9
gopkg.in/urfave/cli%2ev1.Command.startApp(0xa4747e, 0x7, 0x0, 0x0, 0x121597e8, 0
x1, 0x1, 0xa568cb, 0x1c, 0x0, ...)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:29
8 +0x691
gopkg.in/urfave/cli%2ev1.Command.Run(0xa4747e, 0x7, 0x0, 0x0, 0x121597e8, 0x1, 0
x1, 0xa568cb, 0x1c, 0x0, ...)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/command.go:98
 +0xf6a
gopkg.in/urfave/cli%2ev1.(*App).Run(0x124341c0, 0x12047900, 0x3, 0x4, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:255 +0
x566
main.main()
        /home/travis/gopath/src/github.com/Southclaws/sampctl/main.go:314 +0x141
0
```

**Comment by ADRFranklin** [comment]
@Zorono Does this still happen on the latest version, and if so could you give me more information about what's in the directory, permissions, and how it's used etc.
